/*
-- Query: SELECT CARRIER, FLIGHT, MAX(DISTANCE) FROM FLIGHTS
WHERE DISTANCE >= '1000'
GROUP BY CARRIER 
ORDER BY MAX(flight) DESC
LIMIT 0, 1000

-- Date: 2015-10-31 10:52
*/
INSERT INTO `FLIGHTS` (`CARRIER`,`FLIGHT`,`MAX(DISTANCE)`) VALUES (EV,4626,1389);
INSERT INTO `FLIGHTS` (`CARRIER`,`FLIGHT`,`MAX(DISTANCE)`) VALUES (WN,733,2133);
INSERT INTO `FLIGHTS` (`CARRIER`,`FLIGHT`,`MAX(DISTANCE)`) VALUES (OO,4483,1008);
INSERT INTO `FLIGHTS` (`CARRIER`,`FLIGHT`,`MAX(DISTANCE)`) VALUES (MQ,4599,1147);
INSERT INTO `FLIGHTS` (`CARRIER`,`FLIGHT`,`MAX(DISTANCE)`) VALUES (9E,3538,1587);
INSERT INTO `FLIGHTS` (`CARRIER`,`FLIGHT`,`MAX(DISTANCE)`) VALUES (B6,725,2586);
INSERT INTO `FLIGHTS` (`CARRIER`,`FLIGHT`,`MAX(DISTANCE)`) VALUES (DL,1919,2586);
INSERT INTO `FLIGHTS` (`CARRIER`,`FLIGHT`,`MAX(DISTANCE)`) VALUES (AA,1141,2586);
INSERT INTO `FLIGHTS` (`CARRIER`,`FLIGHT`,`MAX(DISTANCE)`) VALUES (US,245,2153);
INSERT INTO `FLIGHTS` (`CARRIER`,`FLIGHT`,`MAX(DISTANCE)`) VALUES (F9,835,1620);
INSERT INTO `FLIGHTS` (`CARRIER`,`FLIGHT`,`MAX(DISTANCE)`) VALUES (VX,399,2586);
INSERT INTO `FLIGHTS` (`CARRIER`,`FLIGHT`,`MAX(DISTANCE)`) VALUES (UA,1545,4963);
INSERT INTO `FLIGHTS` (`CARRIER`,`FLIGHT`,`MAX(DISTANCE)`) VALUES (AS,11,2402);
INSERT INTO `FLIGHTS` (`CARRIER`,`FLIGHT`,`MAX(DISTANCE)`) VALUES (HA,51,4983);
