/*
-- Query: SELECT CARRIER, flight FROM FLIGHTS
WHERE FLIGHT > '4050'
GROUP BY CARRIER
ORDER BY flight DESC
LIMIT 0, 1000

-- Date: 2015-10-31 10:49
*/
INSERT INTO `FLIGHTS` (`CARRIER`,`flight`) VALUES (OO,8500);
INSERT INTO `FLIGHTS` (`CARRIER`,`flight`) VALUES (EV,5708);
INSERT INTO `FLIGHTS` (`CARRIER`,`flight`) VALUES (MQ,4650);
INSERT INTO `FLIGHTS` (`CARRIER`,`flight`) VALUES (WN,4646);
INSERT INTO `FLIGHTS` (`CARRIER`,`flight`) VALUES (9E,4105);
