/*
-- Query: SELECT ORIGIN, CARRIER, DEST, MAX(DISTANCE) FROM FLIGHTS
LIMIT 0, 1000

-- Date: 2015-10-31 10:39
*/
INSERT INTO `TABLE` (`ORIGIN`,`CARRIER`,`DEST`,`MAX(DISTANCE)`) VALUES ('EWR','UA','IAH',4983);
